module.exports = angular.module('deltachat-ui.shared.constants', [])
    .constant('endpointConstant', require('./endpoint.constant'))
    .constant('errorConstant', require('./error.constant'))
    .constant('keyConstant', require('./key.constant'))
    .constant('keyboardConstant', require('./keyboard.constant'))
    .constant('localeConstant', require('./locale.constant'))
    .constant('regexConstant', require('./regex.constant'))
    .constant('routeConstant', require('./route.constant'))
    .constant('sessionStorageKeyConstant', require('./sessionStorageKey.constant'))
    .constant('stateConstant', require('./state.constant'))
    .constant('statusConstant', require('./status.constant'))
;
